export const suggestionsData = [
  {
    id: "6d10b778-c789-45a3-ac1e-097434e0a9c3",
    username: "maria",
    name: "Maria",
    bio: "Bio 6",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: true,
    requester: true,
  },
  {
    id: "39f5424f-7351-4025-b870-aaaa81979ee7",
    username: "sophia",
    name: "Sophia",
    bio: "Bio 7",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: true,
    requesting: false,
    requester: false,
  },
  {
    id: "7fc212f2-8492-4903-a0a1-1b1e6289ff21",
    username: "user9",
    name: "User 9",
    bio: "Bio 9",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "477db17a-d17d-4bbf-8399-fce5b275b479",
    username: "user22",
    name: "User 22",
    bio: "Bio 22",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "c03708ea-2caa-4f8b-ab4e-7f5a9f41d895",
    username: "noviuser.",
    name: "noviuser",
    bio: "noviuser",
    public: true,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "6566fbff-d7c6-457b-ba02-b0b36075fce3",
    username: "emilia",
    name: "Emilia",
    bio: "Bio 3",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: true,
    requesting: false,
    requester: false,
  },
  {
    id: "0e47c108-eefd-4316-a556-3728964e2b74",
    username: "user12",
    name: "User 12",
    bio: "Bio 12",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "c90ae19b-84da-4acf-9eb5-a7846eb4834a",
    username: "user15",
    name: "User 15",
    bio: "Bio 15",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "90f0dd9b-1ebb-4fa4-8b71-85005b54cd4d",
    username: "user14",
    name: "User 14",
    bio: "Bio 14",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: false,
    requester: false,
  },
  {
    id: "416ec181-3652-4b8d-b529-376738098c6f",
    username: "anna",
    name: "Anna",
    bio: "Bio 4",
    public: false,
    photo: null,
    photo_thumbnail: null,
    cover: null,
    cover_thumbnail: null,
    following: false,
    follower: false,
    requesting: true,
    requester: false,
  },
];
